<?php

namespace WalletBundle\Repository;

/**
 * WalletOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WalletOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
