<?php

namespace QuestionBundle\Container;

class QuestionConst {
    const PHOTO_THUMB_SUFFIX = '?imageView2/2/w/375';

    const QUESTION_DEFAULT_WEIGHT = 600000;
    const QUESTION_MAX_WEIGHT = 10000000;

    const QUESTION_EXPIRE_HOURS = 48;

    const QUESTION_STATUS_DEFAULT = 0;
    const QUESTION_STATUS_UNPAID = 1;
    const QUESTION_STATUS_ANSWERING = 2;
    const QUESTION_STATUS_EXPIRED_NO_ANSWER = 3;
    const QUESTION_STATUS_EXPIRED_UNADOPTED = 4;
    const QUESTION_STATUS_ADOPTED = 5;

    const QUESTION_STATUS_TYPE_ALL = 0;
    const QUESTION_STATUS_TYPE_UNSOLVED = 1;
    const QUESTION_STATUS_TYPE_SOLVED = 2;

    const QUESTION_PAY_STATUS_UNPAID = 0;
    const QUESTION_PAY_STATUS_PAYING = 1;
    const QUESTION_PAY_STATUS_PAID = 2;
    const QUESTION_PAY_STATUS_PAY_TO_ANSWER = 3;
    const QUESTION_PAY_STATUS_DEAL = 4;
}
