<?php

namespace AppBundle\Repository;

use UtilBundle\Container\UtilService;
use UtilBundle\Container\TimeUtilService;
use UtilBundle\Container\StringUtilService;

use BaseBundle\Container\BaseConst;

use AppBundle\Entity\AppFeedback;

/**
 * AppFeedbackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppFeedbackRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * cyy, since 1.0
     *
     * 2017-05-22
     *
     * 将用户的意见反馈数据写入数据库
     */
    public function insertAppFeedback($infoArr) {
        $appFeedback = new AppFeedback();

        $fuid = StringUtilService::getGuid();
        $appFeedback->setFuid($fuid);
        $appFeedback->setIsValid(BaseConst::IS_VALID_TRUE);

        $this->updateAppFeedback($appFeedback, $infoArr);

        return $appFeedback;
    }

    /**
     * cyy, since 1.0
     *
     * 2017-05-22
     *
     * 更新意见反馈数据
     */
    public function updateAppFeedback($appFeedback, $infoArr = array()) {
        if (UtilService::isValidArr($infoArr)) {
            while (list($key, $value) = each($infoArr)) {
                $func = 'set' . $key;
                $appFeedback->$func($value);
            }
        }
        $nowTime = TimeUtilService::getCurrentDateTime();
        $appFeedback->setUpdateTime($nowTime);
        $this->_em->persist($appFeedback);
        $this->_em->flush($appFeedback);
        return $appFeedback;
    }
}
