web:
    resource: "@WebBundle/Controller/"
    type:     annotation
    prefix:   /

wallet:
    resource: "@WalletBundle/Controller/"
    type:     annotation
    prefix:   /

place:
    resource: "@PlaceBundle/Controller/"
    type:     annotation
    prefix:   /

question:
    resource: "@QuestionBundle/Controller/"
    type:     annotation
    prefix:   /

util:
    resource: "@UtilBundle/Controller/"
    type:     annotation
    prefix:   /

base:
    resource: "@BaseBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type:     annotation
    prefix:   /
