# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.logger:
        class:     Symfony\Bridge\Monolog\Logger
        arguments: [app]
        calls:
            - [pushHandler, ['@app.logger_handler']]
    app.logger_handler:
        class:     Monolog\Handler\StreamHandler
        arguments: ['%kernel.logs_dir%/%kernel.environment%.app.log', 200]
