<?php

namespace UserBundle\Repository;

use UserBundle\Entity\PhoneAuthCode;

use UtilBundle\Container\TimeUtilService;

use BaseBundle\Container\BaseConst;

/**
 * PhoneAuthCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhoneAuthCodeRepository extends \Doctrine\ORM\EntityRepository {
    /**
     * cyy, since 1.0
     *
     * 2017-05-18
     *
     * 将手机验证码数据写入数据库
     */
    public function insertPhoneAuthCode($telephone, $authCode) {
        $phoneAuthCode = new PhoneAuthCode();
        $phoneAuthCode->setTelephone($telephone);
        $phoneAuthCode->setAuthCode($authCode);
        $phoneAuthCode->setIsValid(BaseConst::IS_VALID_TRUE);

        $this->savePhoneAuthCode($phoneAuthCode);

        return $phoneAuthCode;
    }

    /**
     * cyy, since 1.0
     *
     * 2017-05-18
     *
     * 存储验证码数据
     */
    public function savePhoneAuthCode($phoneAuthCode) {
        $nowTime = TimeUtilService::getCurrentDateTime();
        $phoneAuthCode->setUpdateTime($nowTime);
        $this->_em->persist($phoneAuthCode);
        $this->_em->flush($phoneAuthCode);
    }

    /**
     * cyy, since 1.0
     *
     * 2017-05-18
     *
     * 统计手机号搜索某个时间点之前的验证码数量
     */
    public function countPhoneAuthCodeByTelephone($telephone, $dateTime) {
        $qb = $this->_em->createQueryBuilder();
        $q = $qb->select('count(pac) as Number')
            ->from('UserBundle:PhoneAuthCode', 'pac')
            ->where('pac.isValid = 1')
            ->andWhere('pac.telephone = :Telephone')
            ->andWhere('pac.createTime > :DateTime')
            ->setParameter('Telephone', $telephone)
            ->setParameter('DateTime', $dateTime)
            ->getQuery();
        $result = $q->getResult();

        return $result;
    }
}
