services:
    util.wrapperservice:
        class: UtilBundle\Container\WrapperService
        arguments: ["@doctrine.orm.entity_manager", "@app.logger", "@service_container", "@request_stack"]
#    util.example:
#        class: UtilBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
