<?php

namespace PlaceBundle\Repository;

/**
 * PlaceProvinceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceProvinceRepository extends \Doctrine\ORM\EntityRepository
{
}
