<?php

namespace PlaceBundle\Repository;

/**
 * PlaceCityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceCityRepository extends \Doctrine\ORM\EntityRepository
{
}
