services:
    base.wrapperservice:
        class: BaseBundle\Container\WrapperService
        arguments: ["@doctrine.orm.entity_manager", "@app.logger", "@service_container", "@request_stack"]
#    base.example:
#        class: BaseBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
