services:
    place.placeservice:
        class: PlaceBundle\Container\PlaceService
        arguments: ["@doctrine.orm.entity_manager", "@app.logger", "@service_container", "@request_stack"]
#    place.example:
#        class: PlaceBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
